-- Sprint-4 P2: RBAC 权限模型与初始化数据
-- 说明：
-- 1. 首版继续沿用 sys_user.role（ADMIN / USER）作为角色来源
-- 2. 本脚本仅新增权限点表与角色权限关联表，不强制引入独立角色表
-- 3. 权限编码规范：menu.* / btn.*.* / scope.*.*
-- 4. 本脚本可重复执行，重复执行时会自动更新权限定义并忽略重复授权

CREATE TABLE IF NOT EXISTS sys_permission (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    permission_code VARCHAR(100) NOT NULL COMMENT '权限编码',
    permission_name VARCHAR(100) NOT NULL COMMENT '权限名称',
    permission_type VARCHAR(20) NOT NULL COMMENT '权限类型：MENU / BUTTON / DATA_SCOPE',
    module_key VARCHAR(50) NOT NULL COMMENT '模块标识',
    parent_code VARCHAR(100) DEFAULT NULL COMMENT '父级权限编码',
    route_path VARCHAR(120) DEFAULT NULL COMMENT '前端路由路径，仅菜单权限使用',
    sort_no INT NOT NULL DEFAULT 0 COMMENT '排序值',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
    remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_permission_code (permission_code),
    KEY idx_permission_type_status (permission_type, status),
    KEY idx_permission_module (module_key)
) COMMENT='权限点表';

CREATE TABLE IF NOT EXISTS sys_role_permission (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    role_code VARCHAR(20) NOT NULL COMMENT '角色编码：ADMIN / USER',
    permission_code VARCHAR(100) NOT NULL COMMENT '权限编码',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_role_permission (role_code, permission_code),
    KEY idx_role_code (role_code),
    KEY idx_role_permission_code (permission_code)
) COMMENT='角色权限关联表';

INSERT INTO sys_permission (
    permission_code, permission_name, permission_type, module_key, parent_code, route_path, sort_no, status, remark
) VALUES
    ('menu.home', '首页', 'MENU', 'home', NULL, '/home', 10, 1, '首页菜单'),
    ('menu.activity', '社区活动', 'MENU', 'activity', NULL, '/activity', 20, 1, '社区活动菜单'),
    ('menu.volunteer', '志愿者管理', 'MENU', 'volunteer', NULL, '/volunteer', 30, 1, '志愿者菜单'),
    ('menu.guide', '办事指南', 'MENU', 'guide', NULL, '/guide', 40, 1, '办事指南菜单'),
    ('menu.appointment', '服务预约', 'MENU', 'appointment', NULL, '/appointment', 50, 1, '服务预约菜单'),
    ('menu.neighborhelp', '邻里互助', 'MENU', 'neighborhelp', NULL, '/neighborhelp', 60, 1, '邻里互助菜单'),
    ('menu.points', '积分中心', 'MENU', 'points', NULL, '/points', 70, 1, '积分中心菜单'),
    ('menu.message', '消息中心', 'MENU', 'message', NULL, '/message', 80, 1, '消息中心菜单'),
    ('menu.evaluation', '服务评价', 'MENU', 'evaluation', NULL, '/evaluation', 90, 1, '服务评价菜单'),
    ('menu.workorder', '工单管理', 'MENU', 'workorder', NULL, '/workorder', 100, 1, '工单管理菜单'),
    ('menu.workorder.overtime', '工单超时看板', 'MENU', 'workorder', 'menu.workorder', '/workorder-overtime', 110, 1, '工单超时看板菜单'),
    ('menu.hazard', '治安隐患', 'MENU', 'hazard', NULL, '/hazard', 120, 1, '治安隐患菜单'),
    ('menu.notice', '通知公告', 'MENU', 'notice', NULL, '/notice', 130, 1, '通知公告菜单'),
    ('menu.resident', '居民管理', 'MENU', 'resident', NULL, '/resident', 140, 1, '居民管理菜单'),
    ('menu.floating', '流动人口', 'MENU', 'floating', NULL, '/floating', 150, 1, '流动人口菜单'),
    ('menu.dispatch.rule', '派单规则', 'MENU', 'dispatch_rule', NULL, '/dispatch-rule', 160, 1, '派单规则菜单'),
    ('menu.user', '用户管理', 'MENU', 'user', NULL, '/user', 170, 1, '用户管理菜单'),
    ('menu.log', '操作日志', 'MENU', 'log', NULL, '/log', 180, 1, '操作日志菜单'),
    ('menu.profile', '个人中心', 'MENU', 'profile', NULL, '/profile', 190, 1, '个人中心菜单'),

    ('btn.workorder.add', '提交工单', 'BUTTON', 'workorder', 'menu.workorder', NULL, 1001, 1, '工单新增'),
    ('btn.workorder.edit', '编辑工单', 'BUTTON', 'workorder', 'menu.workorder', NULL, 1002, 1, '工单编辑'),
    ('btn.workorder.delete', '删除工单', 'BUTTON', 'workorder', 'menu.workorder', NULL, 1003, 1, '工单删除'),
    ('btn.workorder.handle', '处理工单', 'BUTTON', 'workorder', 'menu.workorder', NULL, 1004, 1, '工单处理'),
    ('btn.workorder.export', '导出工单', 'BUTTON', 'workorder', 'menu.workorder', NULL, 1005, 1, '工单导出'),
    ('btn.volunteer.apply', '申请志愿者', 'BUTTON', 'volunteer', 'menu.volunteer', NULL, 1101, 1, '志愿者申请'),
    ('btn.volunteer.audit', '审核志愿者', 'BUTTON', 'volunteer', 'menu.volunteer', NULL, 1102, 1, '志愿者审核'),
    ('btn.volunteer.edit', '编辑志愿者', 'BUTTON', 'volunteer', 'menu.volunteer', NULL, 1103, 1, '志愿者编辑'),
    ('btn.volunteer.delete', '删除志愿者', 'BUTTON', 'volunteer', 'menu.volunteer', NULL, 1104, 1, '志愿者删除'),
    ('btn.user.add', '新增用户', 'BUTTON', 'user', 'menu.user', NULL, 1201, 1, '用户新增'),
    ('btn.user.edit', '编辑用户', 'BUTTON', 'user', 'menu.user', NULL, 1202, 1, '用户编辑'),
    ('btn.user.delete', '删除用户', 'BUTTON', 'user', 'menu.user', NULL, 1203, 1, '用户删除'),
    ('btn.dispatch.rule.add', '新增派单规则', 'BUTTON', 'dispatch_rule', 'menu.dispatch.rule', NULL, 1301, 1, '派单规则新增'),
    ('btn.dispatch.rule.edit', '编辑派单规则', 'BUTTON', 'dispatch_rule', 'menu.dispatch.rule', NULL, 1302, 1, '派单规则编辑'),
    ('btn.dispatch.rule.delete', '删除派单规则', 'BUTTON', 'dispatch_rule', 'menu.dispatch.rule', NULL, 1303, 1, '派单规则删除'),
    ('btn.dispatch.rule.preview', '预览派单规则', 'BUTTON', 'dispatch_rule', 'menu.dispatch.rule', NULL, 1304, 1, '派单规则预览'),
    ('btn.notice.add', '发布通知', 'BUTTON', 'notice', 'menu.notice', NULL, 1401, 1, '通知新增'),
    ('btn.notice.edit', '编辑通知', 'BUTTON', 'notice', 'menu.notice', NULL, 1402, 1, '通知编辑'),
    ('btn.notice.delete', '删除通知', 'BUTTON', 'notice', 'menu.notice', NULL, 1403, 1, '通知删除'),
    ('btn.notice.stats', '查看通知统计', 'BUTTON', 'notice', 'menu.notice', NULL, 1404, 1, '通知统计'),

    ('btn.resident.add', '新增居民', 'BUTTON', 'resident', 'menu.resident', NULL, 1501, 1, '居民新增'),
    ('btn.resident.edit', '编辑居民', 'BUTTON', 'resident', 'menu.resident', NULL, 1502, 1, '居民编辑'),
    ('btn.resident.delete', '删除居民', 'BUTTON', 'resident', 'menu.resident', NULL, 1503, 1, '居民删除'),
    ('btn.resident.export', '导出居民', 'BUTTON', 'resident', 'menu.resident', NULL, 1504, 1, '居民导出'),
    ('btn.resident.family.add', '新增家庭关系', 'BUTTON', 'resident', 'menu.resident', NULL, 1505, 1, '家庭关系新增'),
    ('btn.resident.family.delete', '删除家庭关系', 'BUTTON', 'resident', 'menu.resident', NULL, 1506, 1, '家庭关系删除'),
    ('btn.activity.add', '发布活动', 'BUTTON', 'activity', 'menu.activity', NULL, 1601, 1, '活动新增'),
    ('btn.activity.edit', '编辑活动', 'BUTTON', 'activity', 'menu.activity', NULL, 1602, 1, '活动编辑'),
    ('btn.activity.delete', '删除活动', 'BUTTON', 'activity', 'menu.activity', NULL, 1603, 1, '活动删除'),
    ('btn.guide.add', '发布指南', 'BUTTON', 'guide', 'menu.guide', NULL, 1701, 1, '指南新增'),
    ('btn.guide.edit', '编辑指南', 'BUTTON', 'guide', 'menu.guide', NULL, 1702, 1, '指南编辑'),
    ('btn.guide.delete', '删除指南', 'BUTTON', 'guide', 'menu.guide', NULL, 1703, 1, '指南删除'),
    ('btn.appointment.add', '新增预约', 'BUTTON', 'appointment', 'menu.appointment', NULL, 1801, 1, '预约新增'),
    ('btn.appointment.edit', '编辑预约', 'BUTTON', 'appointment', 'menu.appointment', NULL, 1802, 1, '预约编辑'),
    ('btn.appointment.delete', '删除预约', 'BUTTON', 'appointment', 'menu.appointment', NULL, 1803, 1, '预约删除'),
    ('btn.appointment.status.confirm', '确认预约', 'BUTTON', 'appointment', 'menu.appointment', NULL, 1804, 1, '预约确认'),
    ('btn.appointment.status.complete', '完成预约', 'BUTTON', 'appointment', 'menu.appointment', NULL, 1805, 1, '预约完成'),
    ('btn.appointment.status.cancel', '取消预约', 'BUTTON', 'appointment', 'menu.appointment', NULL, 1806, 1, '预约取消'),
    ('btn.neighborhelp.add', '发布互助', 'BUTTON', 'neighborhelp', 'menu.neighborhelp', NULL, 1901, 1, '互助新增'),
    ('btn.neighborhelp.edit', '编辑互助', 'BUTTON', 'neighborhelp', 'menu.neighborhelp', NULL, 1902, 1, '互助编辑'),
    ('btn.neighborhelp.delete', '删除互助', 'BUTTON', 'neighborhelp', 'menu.neighborhelp', NULL, 1903, 1, '互助删除'),
    ('btn.neighborhelp.status.complete', '完成互助', 'BUTTON', 'neighborhelp', 'menu.neighborhelp', NULL, 1904, 1, '互助完成'),
    ('btn.neighborhelp.status.close', '关闭互助', 'BUTTON', 'neighborhelp', 'menu.neighborhelp', NULL, 1905, 1, '互助关闭'),
    ('btn.message.read', '标记消息已读', 'BUTTON', 'message', 'menu.message', NULL, 2001, 1, '消息已读'),
    ('btn.message.read_all', '全部消息已读', 'BUTTON', 'message', 'menu.message', NULL, 2002, 1, '消息全部已读'),
    ('btn.message.admin_list', '查看消息管理列表', 'BUTTON', 'message', 'menu.message', NULL, 2003, 1, '消息管理列表'),
    ('btn.evaluation.submit', '提交评价', 'BUTTON', 'evaluation', 'menu.evaluation', NULL, 2101, 1, '评价提交'),
    ('btn.evaluation.admin_list', '查看评价管理列表', 'BUTTON', 'evaluation', 'menu.evaluation', NULL, 2102, 1, '评价管理列表'),
    ('btn.evaluation.stats', '查看评价统计', 'BUTTON', 'evaluation', 'menu.evaluation', NULL, 2103, 1, '评价统计'),
    ('btn.hazard.add', '上报隐患', 'BUTTON', 'hazard', 'menu.hazard', NULL, 2201, 1, '隐患新增'),
    ('btn.hazard.edit', '编辑隐患', 'BUTTON', 'hazard', 'menu.hazard', NULL, 2202, 1, '隐患编辑'),
    ('btn.hazard.delete', '删除隐患', 'BUTTON', 'hazard', 'menu.hazard', NULL, 2203, 1, '隐患删除'),
    ('btn.hazard.handle', '处理隐患', 'BUTTON', 'hazard', 'menu.hazard', NULL, 2204, 1, '隐患处理'),
    ('btn.floating.add', '登记流动人口', 'BUTTON', 'floating', 'menu.floating', NULL, 2301, 1, '流动人口新增'),
    ('btn.floating.edit', '编辑流动人口', 'BUTTON', 'floating', 'menu.floating', NULL, 2302, 1, '流动人口编辑'),
    ('btn.floating.delete', '删除流动人口', 'BUTTON', 'floating', 'menu.floating', NULL, 2303, 1, '流动人口删除'),
    ('btn.log.delete', '删除日志', 'BUTTON', 'log', 'menu.log', NULL, 2401, 1, '日志删除'),
    ('btn.log.clear', '清空日志', 'BUTTON', 'log', 'menu.log', NULL, 2402, 1, '日志清空'),
    ('btn.profile.update', '修改个人资料', 'BUTTON', 'profile', 'menu.profile', NULL, 2501, 1, '个人资料修改'),
    ('btn.profile.password', '修改个人密码', 'BUTTON', 'profile', 'menu.profile', NULL, 2502, 1, '个人密码修改'),

    ('scope.workorder.self', '工单仅本人', 'DATA_SCOPE', 'workorder', 'menu.workorder', NULL, 3001, 1, '仅查看本人提交的工单'),
    ('scope.workorder.all', '工单全量', 'DATA_SCOPE', 'workorder', 'menu.workorder', NULL, 3002, 1, '查看全部工单'),
    ('scope.appointment.self', '预约仅本人', 'DATA_SCOPE', 'appointment', 'menu.appointment', NULL, 3101, 1, '仅查看本人预约'),
    ('scope.appointment.all', '预约全量', 'DATA_SCOPE', 'appointment', 'menu.appointment', NULL, 3102, 1, '查看全部预约'),
    ('scope.message.self', '消息仅本人', 'DATA_SCOPE', 'message', 'menu.message', NULL, 3201, 1, '仅查看本人消息'),
    ('scope.message.all', '消息全量', 'DATA_SCOPE', 'message', 'menu.message', NULL, 3202, 1, '查看全部消息'),
    ('scope.evaluation.self', '评价仅本人', 'DATA_SCOPE', 'evaluation', 'menu.evaluation', NULL, 3301, 1, '仅查看本人评价'),
    ('scope.evaluation.all', '评价全量', 'DATA_SCOPE', 'evaluation', 'menu.evaluation', NULL, 3302, 1, '查看全部评价'),
    ('scope.volunteer.public_self', '志愿者公开加本人', 'DATA_SCOPE', 'volunteer', 'menu.volunteer', NULL, 3401, 1, '查看已通过志愿者与本人申请'),
    ('scope.volunteer.all', '志愿者全量', 'DATA_SCOPE', 'volunteer', 'menu.volunteer', NULL, 3402, 1, '查看全部志愿者记录'),
    ('scope.notice.published', '公告已发布可见', 'DATA_SCOPE', 'notice', 'menu.notice', NULL, 3501, 1, '仅查看已发布公告'),
    ('scope.notice.all', '公告全量', 'DATA_SCOPE', 'notice', 'menu.notice', NULL, 3502, 1, '查看全部公告')
ON DUPLICATE KEY UPDATE
    permission_name = VALUES(permission_name),
    permission_type = VALUES(permission_type),
    module_key = VALUES(module_key),
    parent_code = VALUES(parent_code),
    route_path = VALUES(route_path),
    sort_no = VALUES(sort_no),
    status = VALUES(status),
    remark = VALUES(remark),
    update_time = CURRENT_TIMESTAMP;

INSERT IGNORE INTO sys_role_permission (role_code, permission_code)
SELECT 'ADMIN', permission_code
FROM sys_permission
WHERE status = 1;

INSERT IGNORE INTO sys_role_permission (role_code, permission_code) VALUES
    ('USER', 'menu.home'),
    ('USER', 'menu.activity'),
    ('USER', 'menu.volunteer'),
    ('USER', 'menu.guide'),
    ('USER', 'menu.appointment'),
    ('USER', 'menu.neighborhelp'),
    ('USER', 'menu.points'),
    ('USER', 'menu.message'),
    ('USER', 'menu.evaluation'),
    ('USER', 'menu.workorder'),
    ('USER', 'menu.hazard'),
    ('USER', 'menu.notice'),
    ('USER', 'menu.profile'),
    ('USER', 'btn.workorder.add'),
    ('USER', 'btn.workorder.edit'),
    ('USER', 'btn.workorder.delete'),
    ('USER', 'btn.volunteer.apply'),
    ('USER', 'btn.volunteer.edit'),
    ('USER', 'btn.volunteer.delete'),
    ('USER', 'btn.appointment.add'),
    ('USER', 'btn.appointment.edit'),
    ('USER', 'btn.appointment.delete'),
    ('USER', 'btn.neighborhelp.add'),
    ('USER', 'btn.neighborhelp.edit'),
    ('USER', 'btn.neighborhelp.delete'),
    ('USER', 'btn.message.read'),
    ('USER', 'btn.message.read_all'),
    ('USER', 'btn.evaluation.submit'),
    ('USER', 'btn.hazard.add'),
    ('USER', 'btn.hazard.edit'),
    ('USER', 'btn.hazard.delete'),
    ('USER', 'btn.profile.update'),
    ('USER', 'btn.profile.password'),
    ('USER', 'scope.workorder.self'),
    ('USER', 'scope.appointment.self'),
    ('USER', 'scope.message.self'),
    ('USER', 'scope.evaluation.self'),
    ('USER', 'scope.volunteer.public_self'),
    ('USER', 'scope.notice.published');

-- 可选验证语句
-- SELECT role_code, COUNT(*) FROM sys_role_permission GROUP BY role_code;
-- SELECT * FROM sys_permission ORDER BY permission_type, sort_no;
